Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -30,8 +30,24 @@ PYTHON_EXE="/app/.heroku/python/bin/python"
 PIP_VERSION="1.3.1"
 DISTRIBUTE_VERSION="0.6.36"
 
+# Setup bpwatch
+export PATH=$PATH:$ROOT_DIR/vendor/bpwatch
+LOGPLEX_KEY="t.b396af7f-ad75-4643-8b9e-ebb288acc624"
+export BPWATCH_STORE_PATH=$CACHE_DIR/bpwatch.json
+BUILDPACK_VERSION=v28
+
+# Support Anvil Build_IDs
+[ ! "$REQUEST_ID" ] && REQUEST_ID=$SLUG_ID
+
 # Sanitizing environment variables.
 unset GIT_DIR PYTHONHOME PYTHONPATH LD_LIBRARY_PATH LIBRARY_PATH
+
+bpwatch init $LOGPLEX_KEY
+bpwatch build python $BUILDPACK_VERSION $REQUEST_ID
+TMP_APP_DIR=$CACHE_DIR/tmp_app_dir
+
+bpwatch start compile
+
 
 # We'll need to send these statics to other scripts we `source`.
 export BUILD_DIR CACHE_DIR BIN_DIR PROFILE_PATH
@@ -44,11 +60,23 @@ APP_DIR='/app'
 TMP_APP_DIR=$CACHE_DIR/tmp_app_dir
 
 # Copy Anvil app dir to temporary storage...
+bpwatch start anvil_appdir_stage
+  if [ "$SLUG_ID" ]; then
+    mkdir -p $TMP_APP_DIR
+    deep-mv $APP_DIR $TMP_APP_DIR
+  else
+    deep-rm $APP_DIR
+  fi
+bpwatch stop anvil_appdir_stage
+
+# Copy Anvil app dir to temporary storage...
 mkdir -p $TMP_APP_DIR
 deep-mv $APP_DIR $TMP_APP_DIR
 
 # Copy Application code in.
-deep-mv $BUILD_DIR $APP_DIR
+bpwatch start appdir_stage
+  deep-mv $BUILD_DIR $APP_DIR
+bpwatch stop appdir_stage
 
 # Set new context.
 ORIG_BUILD_DIR=$BUILD_DIR
@@ -65,7 +93,9 @@ export LD_LIBRARY_PATH=$LIBRARY_PATH
 cd $BUILD_DIR
 
 # Experimental pre_compile hook.
-source $BIN_DIR/steps/hooks/pre_compile
+bpwatch start pre_compile
+  source $BIN_DIR/steps/hooks/pre_compile
+bpwatch stop pre_compile
 
 # If no requirements given, assume `setup.py develop`.
 if [ ! -f requirements.txt ]; then
@@ -83,13 +113,17 @@ fi
 mkdir -p $CACHE_DIR
 
 # Purge "old-style" virtualenvs.
-[ -d $CACHE_DIR/$LEGACY_TRIGGER ] && rm -fr $CACHE_DIR/.heroku/bin $CACHE_DIR/.heroku/lib $CACHE_DIR/.heroku/include
-[ -d $CACHE_DIR/$VIRTUALENV_LOC ] && rm -fr $CACHE_DIR/.heroku/venv $CACHE_DIR/.heroku/src
+bpwatch start clear_old_venvs
+  [ -d $CACHE_DIR/$LEGACY_TRIGGER ] && rm -fr $CACHE_DIR/.heroku/bin $CACHE_DIR/.heroku/lib $CACHE_DIR/.heroku/include
+  [ -d $CACHE_DIR/$VIRTUALENV_LOC ] && rm -fr $CACHE_DIR/.heroku/venv $CACHE_DIR/.heroku/src
+bpwatch stop clear_old_venvs
 
 # Restore old artifacts from the cache.
-for dir in $CACHED_DIRS; do
-  cp -R $CACHE_DIR/$dir . &> /dev/null || true
-done
+bpwatch start restore_cache
+  for dir in $CACHED_DIRS; do
+    cp -R $CACHE_DIR/$dir . &> /dev/null || true
+  done
+bpwatch stop restore_cache
 
 set +e
 # Create set-aside `.heroku` folder.
@@ -104,8 +138,10 @@ PYTHON_VERSION=$(cat runtime.txt)
 # Install Python.
 if [ -f .heroku/python-version ]; then
   if [ ! $(cat .heroku/python-version) = $PYTHON_VERSION ]; then
-    puts-step "Found $(cat .heroku/python-version), removing."
-    rm -fr .heroku/python
+    bpwatch start uninstall_python
+      puts-step "Found $(cat .heroku/python-version), removing."
+      rm -fr .heroku/python
+    bpwatch stop uninstall_python
   else
     SKIP_INSTALL=1
   fi
@@ -113,14 +149,16 @@ fi
 
 
 if [ ! "$SKIP_INSTALL" ]; then
-  puts-step "Preparing Python runtime ($PYTHON_VERSION)"
-  curl http://envy-versions.s3.amazonaws.com/$PYTHON_VERSION.tar.bz2 -s | tar jx &> /dev/null
-  if [[ $? != 0 ]] ; then
-    puts-warn "Requested runtime ($PYTHON_VERSION) was not found."
-    puts-warn "Aborting.  More info: https://devcenter.heroku.com/articles/python-support"
-    exit 1
-  fi
-  mv python .heroku/python
+  bpwatch start install_python
+    puts-step "Preparing Python runtime ($PYTHON_VERSION)"
+    curl http://envy-versions.s3.amazonaws.com/$PYTHON_VERSION.tar.bz2 -s | tar jx &> /dev/null
+    if [[ $? != 0 ]] ; then
+      puts-warn "Requested runtime ($PYTHON_VERSION) was not found."
+      puts-warn "Aborting.  More info: https://devcenter.heroku.com/articles/python-support"
+      exit 1
+    fi
+    mv python .heroku/python
+  bpwatch stop install_python
 
   # Record for future reference.
   echo $PYTHON_VERSION > .heroku/python-version
@@ -135,16 +173,24 @@ fi
 if [ "$FRESH_PYTHON" ] || [[ ! $(pip --version) == *$PIP_VERSION* ]]; then
   WORKING_DIR=$(pwd)
 
-  # Prepare it for the real world
-  puts-step "Installing Distribute ($DISTRIBUTE_VERSION)"
-  cd $ROOT_DIR/vendor/distribute-$DISTRIBUTE_VERSION/
-  python setup.py install &> /dev/null
-  cd $WORKING_DIR
+  bpwatch start prepare_environment
 
-  puts-step "Installing Pip ($PIP_VERSION)"
-  cd $ROOT_DIR/vendor/pip-$PIP_VERSION/
-  python setup.py install &> /dev/null
-  cd $WORKING_DIR
+  bpwatch start install_distribute
+    # Prepare it for the real world
+    puts-step "Installing Distribute ($DISTRIBUTE_VERSION)"
+    cd $ROOT_DIR/vendor/distribute-$DISTRIBUTE_VERSION/
+    python setup.py install &> /dev/null
+    cd $WORKING_DIR
+  bpwatch stop install_distribute
+
+  bpwatch start install_pip
+    puts-step "Installing Pip ($PIP_VERSION)"
+    cd $ROOT_DIR/vendor/pip-$PIP_VERSION/
+    python setup.py install &> /dev/null
+    cd $WORKING_DIR
+
+  bpwatch stop install_pip
+  bpwatch stop prepare_environment
 fi
 
 set -e
@@ -152,21 +198,41 @@ hash -r
 
 # Pylibmc support.
 # See [`bin/steps/pylibmc`](pylibmc.html).
-source $BIN_DIR/steps/pylibmc
+bpwatch start pylibmc_install
+  source $BIN_DIR/steps/pylibmc
+bpwatch stop pylibmc_install
+
+# GeoDjango support. (GEOS, Proj.4, GDAL)
+# See [`bin/steps/geos`](geos.html).
+# See [`bin/steps/proj4`](proj4.html).
+# See [`bin/steps/gdal`](gdal.html).
+bpwatch start geodjango_install
+  source $BIN_DIR/steps/geos
+  source $BIN_DIR/steps/proj4
+  source $BIN_DIR/steps/gdal
+bpwatch stop geodjango_install
 
 # Numpy/scipy support
+bpwatch start numpy-scipy_install
 source $BIN_DIR/steps/numpy-scipy
+bpwatch stop numpy-scipy_install
 
 # Install Mercurial if it appears to be required.
 if (grep -Fiq "hg+" requirements.txt) then
-  /app/.heroku/python/bin/pip install --use-mirrors mercurial | cleanup | indent
+  bpwatch start mercurial_install
+    /app/.heroku/python/bin/pip install --use-mirrors mercurial | cleanup | indent
+  bpwatch stop mercurial_install
 fi
 
 # Force scikit-learn to use a specific script
+bpwatch start scikit-learn_install
 source $BIN_DIR/steps/scikit-learn
+bpwatch stop scikit-learn_install
 
 # NLTK corpora
+bpwatch start nltk-corpora_install
 source $BIN_DIR/steps/nltk-corpora
+bpwatch stop nltk-corpora_install
 
 # Install dependencies with Pip.
 puts-step "Installing dependencies using Pip ($PIP_VERSION)"
@@ -175,7 +241,9 @@ puts-step "Installing dependencies using Pip ($PIP_VERSION)"
 /app/.heroku/python/bin/pip install --use-mirrors -r requirements.txt --exists-action=w --src=./.heroku/src | cleanup | indent
 
 # Django collectstatic support.
-source $BIN_DIR/steps/collectstatic
+bpwatch start collectstatic
+  source $BIN_DIR/steps/collectstatic
+bpwatch stop collectstatic
 
 # ### Finalize
 #
@@ -185,6 +253,9 @@ set-env NLTK_DATA /app/.heroku/nltk_data
 set-env PATH '$HOME/.heroku/python/bin:$PATH'
 set-env PYTHONUNBUFFERED true
 set-env PYTHONHOME /app/.heroku/python
+set-env GEOS_LIBRARY_PATH $GEOS_LIBRARY_PATH
+set-env PROJ4_LIBRARY_PATH $PROJ4_LIBRARY_PATH
+set-env GDAL_LIBRARY_PATH $GDAL_LIBRARY_PATH
 set-default-env LIBRARY_PATH $LIBRARY_PATH
 set-default-env LD_LIBRARY_PATH $LD_LIBRARY_PATH
 set-default-env LANG en_US.UTF-8
